Do not prescribe numeric array indices in setParameters
The following code broke:

```php
        $parameters = $execute->getParameters();
        $parameters[] = $parameter;

        $execute->setParameters($parameters);
```

```
Error: Cannot unpack array with string keys

/home/benedikt/projects/sailor/vendor/nette/php-generator/src/PhpGenerator/Traits/FunctionLike.php:72
```